#Descion Tree to predict if home market in area is hot or cold

In [2]:
folder_path = "./"
file_name = "singlefamilyhome_time_city.csv"

In [5]:
import pandas as pd
home_df = pd.read_csv("metro_heat_index.csv")
print(home_df)

     RegionID  SizeRank       RegionName RegionType StateName  2018-01-31  \
0      102001         0    United States    country       NaN        49.0
1      394913         1     New York, NY        msa        NY        53.0
2      753899         2  Los Angeles, CA        msa        CA        68.0
3      394463         3      Chicago, IL        msa        IL        48.0
4      394514         4       Dallas, TX        msa        TX        55.0
..        ...       ...              ...        ...       ...         ...
923    753929       935       Zapata, TX        msa        TX         NaN
924    394743       936    Ketchikan, AK        msa        AK        38.0
925    753874       937        Craig, CO        msa        CO         6.0
926    395188       938       Vernon, TX        msa        TX        51.0
927    394767       939       Lamesa, TX        msa        TX        46.0

     2018-02-28  2018-03-31  2018-04-30  2018-05-31  ...  2023-12-31  \
0          50.0        52.0        54.0        55.0  ...        56.0
1          52.0        55.0        57.0        56.0  ...        75.0
2          65.0        65.0        66.0        65.0  ...        77.0
3          49.0        51.0        52.0        50.0  ...        62.0
4          55.0        58.0        60.0        59.0  ...        62.0
..          ...         ...         ...         ...  ...         ...
923         NaN         NaN         NaN         NaN  ...        32.0
924        36.0        36.0        38.0        49.0  ...        56.0
925        26.0        54.0        68.0        58.0  ...        56.0
926        44.0         NaN        48.0        65.0  ...        63.0
927        45.0        43.0        49.0        50.0  ...        53.0

     2024-01-31  2024-02-29  2024-03-31  2024-04-30  2024-05-31  2024-06-30  \
0          59.0        62.0        63.0        62.0        59.0        57.0
1          85.0        92.0        89.0        87.0        81.0        77.0
2          81.0        84.0        82.0        80.0        74.0        70.0
3          68.0        74.0        76.0        75.0        71.0        67.0
4          66.0        67.0        67.0        65.0        60.0        55.0
..          ...         ...         ...         ...         ...         ...
923        35.0        37.0        34.0        28.0        40.0        53.0
924         NaN        73.0        69.0        51.0        51.0        61.0
925        67.0        62.0        56.0        61.0        59.0        51.0
926        77.0        83.0        79.0        64.0        66.0        62.0
927        54.0        47.0        44.0        47.0        47.0        41.0

     2024-07-31  2024-08-31  2024-09-30
0          55.0        53.0        52.0
1          76.0        76.0        74.0
2          67.0        64.0        63.0
3          64.0        60.0        58.0
4          52.0        49.0        48.0
..          ...         ...         ...
923        47.0        33.0        28.0
924        65.0        57.0        52.0
925        36.0        25.0        22.0
926        54.0        55.0        58.0
927        38.0        37.0        41.0

[928 rows x 86 columns]

In [48]:
# Features
# RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,CountyName
# Target
# 2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,2000-08-31, ...
#6181,0,New York,city,NY,NY,"New York-Newark-Jersey City, NY-NJ-PA",Queens County,245291.08005117264,246606.23387442427,247971.2943357786,250526.64939858264,

#training_features = ["RegionID", "SizeRank", "RegionName", "RegionType", "StateName", "State", "Metro", "CountyName"]
#string_features = ["RegionName", "RegionType", "StateName", "State", "Metro", "CountyName"]
#print(home_data)


       # = le.fit_transform(home_data[feature][i])
    

#print(home_data)

In [49]:
# dictionary to store region name to its ID
#print(home_df["StateName"])

In [11]:
from sklearn.model_selection import train_test_split

# Features
features = [["RegionID", "SizeRank", "StateName"]]
state_to_number = {}

#encode each state to 0-49, without repeating
def encode_state(state):
    if state not in state_to_number:
        state_to_number[state] = len(state_to_number)
    return state_to_number[state]

home_df['StateName'] = home_df['StateName'].apply(encode_state)

#remove nan values
home_df = home_df.dropna()
print(home_df)
#print(features_cleaned)

# Split the data into features and target
features_cleaned = home_df[["RegionID", "SizeRank", "StateName"]]
target_cleaned = home_df.drop(columns=["RegionID", "SizeRank", "RegionName", "RegionType", "StateName"])

print(features_cleaned)
print(target_cleaned)

     RegionID  SizeRank       RegionName RegionType  StateName  2018-01-31  \
0      102001         0    United States    country          0        49.0
1      394913         1     New York, NY        msa          1        53.0
2      753899         2  Los Angeles, CA        msa          2        68.0
3      394463         3      Chicago, IL        msa          3        48.0
4      394514         4       Dallas, TX        msa          4        55.0
..        ...       ...              ...        ...        ...         ...
918    394342       929     Atchison, KS        msa         38        33.0
919    753880       930    Fairfield, IA        msa         37        20.0
921    395142       933   Sweetwater, TX        msa          4        38.0
922    394968       934        Pecos, TX        msa          4        48.0
925    753874       937        Craig, CO        msa         14         6.0

     2018-02-28  2018-03-31  2018-04-30  2018-05-31  ...  2023-12-31  \
0          50.0        52.0        54.0        55.0  ...        56.0
1          52.0        55.0        57.0        56.0  ...        75.0
2          65.0        65.0        66.0        65.0  ...        77.0
3          49.0        51.0        52.0        50.0  ...        62.0
4          55.0        58.0        60.0        59.0  ...        62.0
..          ...         ...         ...         ...  ...         ...
918        41.0        44.0        37.0        37.0  ...        40.0
919        24.0        31.0        34.0        31.0  ...        56.0
921        39.0        41.0        44.0        46.0  ...        46.0
922        49.0        51.0        53.0        53.0  ...        50.0
925        26.0        54.0        68.0        58.0  ...        56.0

     2024-01-31  2024-02-29  2024-03-31  2024-04-30  2024-05-31  2024-06-30  \
0          59.0        62.0        63.0        62.0        59.0        57.0
1          85.0        92.0        89.0        87.0        81.0        77.0
2          81.0        84.0        82.0        80.0        74.0        70.0
3          68.0        74.0        76.0        75.0        71.0        67.0
4          66.0        67.0        67.0        65.0        60.0        55.0
..          ...         ...         ...         ...         ...         ...
918        61.0        81.0        82.0        69.0        64.0        54.0
919        50.0        44.0        40.0        48.0        45.0        44.0
921        50.0        55.0        51.0        51.0        48.0        45.0
922        53.0        55.0        55.0        53.0        51.0        48.0
925        67.0        62.0        56.0        61.0        59.0        51.0

     2024-07-31  2024-08-31  2024-09-30
0          55.0        53.0        52.0
1          76.0        76.0        74.0
2          67.0        64.0        63.0
3          64.0        60.0        58.0
4          52.0        49.0        48.0
..          ...         ...         ...
918        50.0        52.0        49.0
919        41.0        39.0        34.0
921        39.0        37.0        31.0
922        46.0        44.0        44.0
925        36.0        25.0        22.0

[723 rows x 86 columns]
     RegionID  SizeRank  StateName
0      102001         0          0
1      394913         1          1
2      753899         2          2
3      394463         3          3
4      394514         4          4
..        ...       ...        ...
918    394342       929         38
919    753880       930         37
921    395142       933          4
922    394968       934          4
925    753874       937         14

[723 rows x 3 columns]
     2018-01-31  2018-02-28  2018-03-31  2018-04-30  2018-05-31  2018-06-30  \
0          49.0        50.0        52.0        54.0        55.0        53.0
1          53.0        52.0        55.0        57.0        56.0        52.0
2          68.0        65.0        65.0        66.0        65.0        63.0
3          48.0        49.0        51.0        52.0        50.0        48.0
4          55.0        55.0        58.0        60.0        59.0        55.0
..          ...         ...         ...         ...         ...         ...
918        33.0        41.0        44.0        37.0        37.0        40.0
919        20.0        24.0        31.0        34.0        31.0        31.0
921        38.0        39.0        41.0        44.0        46.0        44.0
922        48.0        49.0        51.0        53.0        53.0        50.0
925         6.0        26.0        54.0        68.0        58.0        41.0

     2018-07-31  2018-08-31  2018-09-30  2018-10-31  ...  2023-12-31  \
0          52.0        50.0        48.0        47.0  ...        56.0
1          53.0        53.0        50.0        47.0  ...        75.0
2          60.0        57.0        55.0        54.0  ...        77.0
3          46.0        45.0        43.0        42.0  ...        62.0
4          51.0        50.0        49.0        49.0  ...        62.0
..          ...         ...         ...         ...  ...         ...
918        41.0        37.0        38.0        40.0  ...        40.0
919        31.0        33.0        32.0        27.0  ...        56.0
921        41.0        36.0        43.0        48.0  ...        46.0
922        48.0        47.0        46.0        45.0  ...        50.0
925        26.0        22.0        20.0        26.0  ...        56.0

     2024-01-31  2024-02-29  2024-03-31  2024-04-30  2024-05-31  2024-06-30  \
0          59.0        62.0        63.0        62.0        59.0        57.0
1          85.0        92.0        89.0        87.0        81.0        77.0
2          81.0        84.0        82.0        80.0        74.0        70.0
3          68.0        74.0        76.0        75.0        71.0        67.0
4          66.0        67.0        67.0        65.0        60.0        55.0
..          ...         ...         ...         ...         ...         ...
918        61.0        81.0        82.0        69.0        64.0        54.0
919        50.0        44.0        40.0        48.0        45.0        44.0
921        50.0        55.0        51.0        51.0        48.0        45.0
922        53.0        55.0        55.0        53.0        51.0        48.0
925        67.0        62.0        56.0        61.0        59.0        51.0

     2024-07-31  2024-08-31  2024-09-30
0          55.0        53.0        52.0
1          76.0        76.0        74.0
2          67.0        64.0        63.0
3          64.0        60.0        58.0
4          52.0        49.0        48.0
..          ...         ...         ...
918        50.0        52.0        49.0
919        41.0        39.0        34.0
921        39.0        37.0        31.0
922        46.0        44.0        44.0
925        36.0        25.0        22.0

[723 rows x 81 columns]

In [ ]:
# split data into training and testing sets using temporal split
# data goes from 1/31/18 to 9/30/24 (monthly) total of 81 months
# training: 1/31/18 to 12/31/22
# testing: 1/31/23 to 9/30/24

# Split the data into training, validation, and testing sets
# Define the split points
train_end = '2022-12-31'
test_start = '2023-01-31'

# Split the data
X_train = features_cleaned.loc[:, features_cleaned.columns]
y_train = target_cleaned.loc[:, :'2022-12-31']

X_test = features_cleaned.loc[:, features_cleaned.columns]
y_test = target_cleaned.loc[:, '2023-01-31':]

"""""
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)
"""

(723, 3)
(723, 60)
(723, 3)
(723, 21)

In [16]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Create a random forest regressor
rf = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model
rf.fit(X_train, y_train)

# Make predictions
train_preds = rf.predict(X_train)
test_preds = rf.predict(X_test)

# Score the model

train_mse = mean_squared_error(y_train, train_preds)
train_r2 = r2_score(y_train, train_preds)

#test_mse = mean_squared_error(y_test, test_preds)
#test_r2 = r2_score(y_test, test_preds)

print(f"Train MSE: {train_mse}")
print(f"Train R^2: {train_r2}")

#print(f"Test MSE: {test_mse}")
#print(f"Test R^2: {test_r2}")

Train MSE: 31.736895979714156
Train R^2: 0.8807571384142718